# Generated by Django 5.2.3 on 2025-07-08 06:01

import caregiver.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(validators=[caregiver.models.validate_min_age])),
                ('experience', models.PositiveIntegerField(validators=[caregiver.models.validate_experience])),
                ('speciality', models.CharField(choices=[('Personal Care', 'Personal Care'), ('Companion Care', 'Companion Care'), ('Dementia Care', 'Dementia Care'), ('Mobility Assistance', 'Mobility Assistance'), ('Medication Management', 'Medication Management')], default='Personal Care', max_length=50)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
