# Generated by Django 5.1.7 on 2025-03-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('skills', models.TextField()),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
