# Generated by Django 5.1.7 on 2025-03-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiver',
            name='skills',
        ),
        migrations.AddField(
            model_name='caregiver',
            name='speciality',
            field=models.CharField(choices=[('Personal Care', 'Personal Care'), ('Companion Care', 'Companion Care'), ('Dementia Care', 'Dementia Care'), ('Mobility Assistance', 'Mobility Assistance'), ('Medication Management', 'Medication Management')], default='Personal Care', max_length=50),
        ),
    ]
