# Generated by Django 5.1.7 on 2025-03-27 03:01

import caregiver.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0002_remove_caregiver_skills_caregiver_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='age',
            field=models.IntegerField(validators=[caregiver.models.validate_min_age]),
        ),
    ]
