# Generated by Django 5.1.7 on 2025-03-27 04:27

import caregiver.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0003_alter_caregiver_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='age',
            field=models.PositiveIntegerField(validators=[caregiver.models.validate_min_age]),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='experience',
            field=models.PositiveIntegerField(validators=[caregiver.models.validate_experience]),
        ),
    ]
