# Generated by Django 5.1.7 on 2025-03-27 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('duration', models.IntegerField(help_text='Duration in months')),
                ('requirements', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_records', to='caregiver.caregiver')),
            ],
        ),
    ]
