# Generated by Django 5.1.7 on 2025-03-28 01:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0006_hiringrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='caregivers/'),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
