# Generated by Django 5.1.7 on 2025-03-28 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0007_caregiver_created_at_caregiver_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiver',
            name='image',
        ),
    ]
