# Generated by Django 5.1.7 on 2025-03-28 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0008_remove_caregiver_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiver',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='caregiver',
            name='updated_at',
        ),
    ]
