# Generated by Django 5.1.7 on 2025-03-28 05:59

import caregiver.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0009_remove_caregiver_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringrecord',
            name='duration',
            field=models.IntegerField(help_text='Duration in months', validators=[caregiver.models.validate_duration]),
        ),
        migrations.AlterField(
            model_name='hiringrecord',
            name='start_date',
            field=models.DateField(validators=[caregiver.models.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address_line1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.URLField(blank=True, default=''),
        ),
    ]
